# Table of Contents
 <p><div class="lev1 toc-item"><a href="#MICS-Whales" data-toc-modified-id="MICS-Whales-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>MICS Whales</a></div><div class="lev2 toc-item"><a href="#Import-statements" data-toc-modified-id="Import-statements-11"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Import statements</a></div><div class="lev2 toc-item"><a href="#Ideas" data-toc-modified-id="Ideas-12"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Ideas</a></div><div class="lev3 toc-item"><a href="#Estimating-Birth-rate,-given-that-we-know-a-whale-gave-birth-at-time-t=i" data-toc-modified-id="Estimating-Birth-rate,-given-that-we-know-a-whale-gave-birth-at-time-t=i-121"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Estimating Birth rate, given that we know a whale gave birth at time t=i</a></div><div class="lev3 toc-item"><a href="#Comparing-old-data-with-the-new-data." data-toc-modified-id="Comparing-old-data-with-the-new-data.-122"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Comparing old data with the new data.</a></div><div class="lev2 toc-item"><a href="#Import-statement" data-toc-modified-id="Import-statement-13"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Import statement</a></div><div class="lev2 toc-item"><a href="#Data-Cleaning" data-toc-modified-id="Data-Cleaning-14"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Data Cleaning</a></div><div class="lev3 toc-item"><a href="#Ensure-columns-are-in-string-format" data-toc-modified-id="Ensure-columns-are-in-string-format-141"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Ensure columns are in string format</a></div><div class="lev3 toc-item"><a href="#column_years" data-toc-modified-id="column_years-142"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>column_years</a></div><div class="lev3 toc-item"><a href="#Focus-only-on-raw-unprocessed-data" data-toc-modified-id="Focus-only-on-raw-unprocessed-data-143"><span class="toc-item-num">1.4.3&nbsp;&nbsp;</span>Focus only on raw unprocessed data</a></div><div class="lev3 toc-item"><a href="#Focus-on-part-of-the-data-that-was-sighted-to-have-at-least-one-birth" data-toc-modified-id="Focus-on-part-of-the-data-that-was-sighted-to-have-at-least-one-birth-144"><span class="toc-item-num">1.4.4&nbsp;&nbsp;</span>Focus on part of the data that was sighted to have at least one birth</a></div><div class="lev3 toc-item"><a href="#For-each-row,-find-the-earliest-instance-of-2.0" data-toc-modified-id="For-each-row,-find-the-earliest-instance-of-2.0-145"><span class="toc-item-num">1.4.5&nbsp;&nbsp;</span>For each row, find the earliest instance of 2.0</a></div><div class="lev2 toc-item"><a href="#Causal-Diagram" data-toc-modified-id="Causal-Diagram-15"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Causal Diagram</a></div>

# MICS Whales

## Import statements

## Ideas

Observations about the data set.
* Some individuals are more represented since they're older and had more of a longer time to be sexually active. Thus, our estimates might be biased towards older whales.

* We are missing data. We don't know what happened with a whale when it's been missing for a while. Did it die? Or was it alive, and if so, did it give birth?

* Back-to-back births seem implausible.

### Estimating Birth rate, given that we know a whale gave birth at time t=i
* Problem with "Years Since Previous Birth"
    * _YSPB_ is a noisy variable, since we don't always get the chance to see the whales. If we discard the scenarios where we don't see the whale, then _YSPB_ will be an overestimate of the true concept.
    
    * Idea: Assume a binomial (or negative binomial) distribution
        * it's discrete, and assumes that data is independent and identically distributed (i.i.d.), which isn't exactly always the case (e.g. birth at t=0 gives you a lot of information about birth at t=1. However, maybe it does happen but just very infrequently). 
            * We can just truncate birth at t=1 to never happen, and then we can normalize the other probabilities so they sum to 1.
        * Pick a p.
        * Randomly generate data from this distribution
        * Assess how good the fit is (using uncensored data).
        * Rank the best parameters.
            

        
    * If we're interested in making a statement about whales that should technically be able to reproduce (i.e. active), whatever value we get might be an over-estimate of the true value for active whales. Why? Selection bias. Maybe it's so bad out there that some whales who just matured enough (haven't reproduced) don't get to reproduce. 

### Comparing old data with the new data.
* Maybe individuals (which are more represented in both data sets) are less likely to reproduce when they hit a certain age. So age would be a common cause (confounding variable) of fecundity rate at earlier and later times.


## Import statement

In [10]:
import pandas as pd
import numpy as np

## Data Cleaning

In [7]:
calving_data = pd.read_excel('./data/females_calving_2016 up to date.xlsx')
calving_data

MICS   HWC numbers   80  81   82   83                    84   85   86  \
0    H002          3229  1.0 NaN  NaN  1.0                     1  NaN  NaN   
1    H004          1422  NaN NaN  1.0  2.0                   NaN  NaN  NaN   
2    H008          1417  NaN NaN  2.0  1.0                     1  2.0  NaN   
3    H009          1419  NaN NaN  1.0  NaN                   NaN  NaN  NaN   
4    H035          2088  NaN NaN  1.0  NaN                   NaN  NaN  NaN   
5    H042          1451  NaN NaN  NaN  1.0                     1  NaN  NaN   
6    H044          1424  NaN NaN  1.0  1.0                   NaN  1.0  1.0   
7    H065          7002  NaN NaN  NaN  NaN                   NaN  1.0  NaN   
8    H067          7014  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
9    H102           NaN  NaN NaN  NaN  NaN                     1  1.0  NaN   
10   H103          0274  NaN NaN  NaN  NaN                     1  NaN  NaN   
11   H109          1492  NaN NaN  NaN  NaN                   NaN  1.0  NaN   
12   H118          1491  NaN NaN  NaN  NaN                   NaN  1.0  NaN   
13   H135          3090  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
14   H137          7013  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
15   H140          7015  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
16   H141          0449  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
17   H144          7008  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
18   H147          7019  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
19   H148          2319  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
20   H150          7020  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
21   H157          7018  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
22   H164          7032  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
23   H166          7028  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
24   H168          1452  NaN NaN  1.0  NaN                   NaN  NaN  NaN   
25   H169          7029  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
26   H212          7066  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
27   H216          7068  NaN NaN  NaN  1.0                   NaN  NaN  NaN   
28   H228          7070  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
29   H231          7116  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
..    ...           ...  ...  ..  ...  ...                   ...  ...  ...   
97   H712           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
98   H716           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
99   H719           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
100  H721           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
101  H725           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
102  H728           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
103  H729           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
104  H731           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
105  H738           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
106  H745           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
107  H747           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
108  H748           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
109  H752           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
110  H753           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
111  H782           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
112  H788           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
113  H798           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
114   NaN  new cow 2016  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
115   NaN           NaN  NaN NaN  NaN  NaN                   NaN  NaN  NaN   
116   NaN           NaN  Na

### Ensure columns are in string format

In [24]:
calving_data.columns = calving_data.columns.astype('str')
calving_data.columns

Index(['MICS', 'HWC numbers', '80', '81', '82', '83', '84', '85', '86', '87',
       '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99',
       '00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11',
       '12', '13', '14', '15', '16', 'Unnamed: 39'],
      dtype='object')

### column_years

In [17]:
def column_years():
    col_years = [str(i) for i in range(80,100)]
    
    for i in range(0,17):
        str_val = ''

        if len(str(i)) == 1:
            str_val = '0' + str(i)
        else:
            str_val = str(i)

        col_years.append(str_val)
        
    return col_years

In [18]:
column_years()

['80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '00',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16']

### Focus only on raw unprocessed data

In [31]:
unprocessed_data = calving_data[column_years()].loc[:114]
unprocessed_data

80  81   82   83   84   85   86   87   88   89 ...    07   08   09   10  \
0    1.0 NaN  NaN  1.0    1  NaN  NaN  1.0  1.0  2.0 ...   2.0  1.0  1.0  1.0   
1    NaN NaN  1.0  2.0  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  NaN  1.0  1.0   
2    NaN NaN  2.0  1.0    1  2.0  NaN  NaN  1.0  2.0 ...   1.0  1.0  1.0  1.0   
3    NaN NaN  1.0  NaN  NaN  NaN  NaN  1.0  1.0  1.0 ...   1.0  2.0  1.0  1.0   
4    NaN NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
5    NaN NaN  NaN  1.0    1  NaN  NaN  1.0  2.0  1.0 ...   1.0  2.0  1.0  1.0   
6    NaN NaN  1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0 ...   2.0  1.0  NaN  2.0   
7    NaN NaN  NaN  NaN  NaN  1.0  NaN  1.0  1.0  NaN ...   NaN  NaN  NaN  NaN   
8    NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN ...   NaN  NaN  NaN  NaN   
9    NaN NaN  NaN  NaN    1  1.0  NaN  NaN  NaN  NaN ...   NaN  1.0  NaN  NaN   
10   NaN NaN  NaN  NaN    1  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
11   NaN NaN  NaN  NaN  NaN  1.0  NaN  1.0  1.0  1.0 ...   2.0  1.0  1.0  2.0   
12   NaN NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN ...   1.0  NaN  1.0  NaN   
13   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
14   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  2.0 ...   NaN  NaN  NaN  NaN   
15   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0 ...   1.0  2.0  1.0  1.0   
16   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN ...   1.0  2.0  1.0  1.0   
17   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0 ...   2.0  1.0  1.0  2.0   
18   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  NaN  NaN  NaN   
19   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  NaN  NaN  NaN   
20   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  1.0  1.0  2.0   
21   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  NaN  NaN  NaN   
22   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  2.0  1.0  NaN   
23   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  1.0  NaN  1.0   
24   NaN NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  2.0  1.0  1.0   
25   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
26   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   2.0  NaN  NaN  NaN   
27   NaN NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
28   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   2.0  1.0  1.0  2.0   
29   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
..   ...  ..  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...  ...   
85   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  1.0  1.0   
86   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  1.0  1.0   
87   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  NaN  NaN   
88   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
89   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
90   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
91   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  1.0  NaN   
92   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  1.0  NaN   
93   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  NaN  1.0   
94   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  NaN  1.0   
95   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  1.0  NaN   
96   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
97   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
98   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
99   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  NaN  NaN   
100  NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
101  NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  1.0  1.0  1.0   
102  NaN NaN  NaN  NaN  NaN  NaN  NaN

In [69]:
no_nans = unprocessed_data.fillna(0.0)
no_nans

80   81   82   83   84   85   86   87   88   89 ...    07   08   09  \
0    1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  2.0 ...   2.0  1.0  1.0   
1    0.0  0.0  1.0  2.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  1.0   
2    0.0  0.0  2.0  1.0  1.0  2.0  0.0  0.0  1.0  2.0 ...   1.0  1.0  1.0   
3    0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0 ...   1.0  2.0  1.0   
4    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
5    0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  2.0  1.0 ...   1.0  2.0  1.0   
6    0.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0 ...   2.0  1.0  0.0   
7    0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0 ...   0.0  0.0  0.0   
8    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   0.0  0.0  0.0   
9    0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  0.0   
10   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
11   0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  1.0 ...   2.0  1.0  1.0   
12   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  1.0   
13   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
14   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  2.0 ...   0.0  0.0  0.0   
15   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0 ...   1.0  2.0  1.0   
16   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   1.0  2.0  1.0   
17   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0 ...   2.0  1.0  1.0   
18   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0   
19   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0   
20   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  1.0  1.0   
21   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0   
22   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  2.0  1.0   
23   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  0.0   
24   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  2.0  1.0   
25   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
26   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  0.0  0.0   
27   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
28   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  1.0  1.0   
29   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...   
85   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  1.0   
86   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  1.0   
87   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  0.0   
88   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  0.0   
89   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  0.0   
90   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  0.0   
91   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  1.0   
92   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  1.0   
93   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  0.0   
94   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  0.0   
95   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  1.0   
96   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  0.0   
97   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  0.0   
98   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  0.0   
99   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  0.0   
100  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  0.0   
101  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  1.0   
102  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  1.0   
103  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  0.0   
104  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  1.0   
10

### Focus on part of the data that was sighted to have at least one birth

In [93]:
rows_with_observed_births = no_nans.loc[np.where((no_nans > 1).sum(axis=1) > 0)]
rows_with_observed_births

80   81   82   83   84   85   86   87   88   89 ...    07   08   09  \
0    1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  2.0 ...   2.0  1.0  1.0   
1    0.0  0.0  1.0  2.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  1.0   
2    0.0  0.0  2.0  1.0  1.0  2.0  0.0  0.0  1.0  2.0 ...   1.0  1.0  1.0   
3    0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0 ...   1.0  2.0  1.0   
5    0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  2.0  1.0 ...   1.0  2.0  1.0   
6    0.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0 ...   2.0  1.0  0.0   
8    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   0.0  0.0  0.0   
9    0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  0.0   
11   0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  1.0 ...   2.0  1.0  1.0   
12   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  1.0   
14   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  2.0 ...   0.0  0.0  0.0   
15   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0 ...   1.0  2.0  1.0   
16   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   1.0  2.0  1.0   
17   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0 ...   2.0  1.0  1.0   
19   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0   
20   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  1.0  1.0   
22   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  2.0  1.0   
23   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  0.0   
24   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  2.0  1.0   
26   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  0.0  0.0   
28   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  1.0  1.0   
32   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  2.0   
33   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  1.0  0.0   
34   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  1.0  1.0   
36   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
37   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  2.0   
38   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
40   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  1.0  1.0   
41   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  2.0  1.0   
42   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  1.0  1.0   
43   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  2.0   
45   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  1.0  0.0   
50   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  1.0   
55   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
56   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  2.0   
58   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  1.0  2.0   
59   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
60   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  2.0  0.0   
61   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  1.0  1.0   
64   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  2.0  1.0   
71   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   2.0  1.0  0.0   
72   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  2.0   
78   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  1.0   
79   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  2.0  0.0   
105  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  2.0  0.0   
114  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

      10   11   12   13   14   15   16  
0    1.0  1.0  1.0  1.0  1.0  2.0  1.0  
1    1.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    1.0  1.0  1.0  0.0  1.0  1.0  2.0  
3    1.0  1.0  1.0  1.0  1.0  2.0  1.0  
5    1.0  1.0  0.0  1.0  1.0  1.0  2.0  
6    2.0  0.0  0.0  0.0  0.0  0.0  0.0  
8    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9    0.0  1.0  1.0  0.0  1.0  1.0  1.0  
11   2.0  1.0  1.

### For each row, find the earliest instance of 2.0

In [103]:
def find_earliest_birth(x):
    print(np.where(x == 2))
    for index, i in enumerate(x):
        if i == 2:
            return index
    
    return None

In [104]:
rows_with_observed_births.apply(find_earliest_birth, axis=1)

(array([ 9, 13, 17, 23, 27, 35]),)
(array([ 3, 11, 17, 21, 25]),)
(array([ 2,  5,  9, 14, 17, 19, 24, 26, 36]),)
(array([11, 14, 17, 21, 23, 25, 28, 35]),)
(array([ 8, 11, 13, 16, 25, 28, 36]),)
(array([18, 21, 24, 27, 30]),)
(array([19]),)
(array([25]),)
(array([13, 16, 23, 25, 27, 30]),)
(array([21, 25]),)
(array([9]),)
(array([10, 19, 23, 25, 28]),)
(array([14, 18, 25, 28, 33]),)
(array([20, 25, 27, 30, 33]),)
(array([13]),)
(array([17, 23, 30]),)
(array([17, 22, 28]),)
(array([21, 23, 25]),)
(array([10, 19, 26, 28, 31, 35]),)
(array([25, 27]),)
(array([25, 27, 30]),)
(array([29]),)
(array([17, 25, 27]),)
(array([19, 23, 27, 30, 35]),)
(array([31]),)
(array([18, 25, 29]),)
(array([17, 22, 24, 26]),)
(array([18, 24, 27, 30, 33]),)
(array([26, 28, 31]),)
(array([27]),)
(array([18, 21, 26, 29, 32]),)
(array([27, 31]),)
(array([25, 30]),)
(array([33]),)
(array([26, 29]),)
(array([27, 29]),)
(array([25]),)
(array([28, 31]),)
(array([27, 32]),)
(array([28, 31]),)
(array([27, 30, 34]),)
(a

0       9
1       3
2       2
3      11
5       8
6      18
8      19
9      25
11     13
12     21
14      9
15     10
16     14
17     20
19     13
20     17
22     17
23     21
24     10
26     25
28     25
32     29
33     17
34     19
36     31
37     18
38     17
40     18
41     26
42     27
43     18
45     27
50     25
55     33
56     26
58     27
59     25
60     28
61     27
64     28
71     27
72     29
78     25
79     28
105    28
114    36
dtype: int64

In [54]:
unprocessed_data.loc[0][['89', '90']]

89      2
90    NaN
Name: 0, dtype: object

In [46]:
unprocessed_data

80  81   82   83   84   85   86   87   88   89 ...    07   08   09   10  \
0    1.0 NaN  NaN  1.0    1  NaN  NaN  1.0  1.0  2.0 ...   2.0  1.0  1.0  1.0   
1    NaN NaN  1.0  2.0  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  NaN  1.0  1.0   
2    NaN NaN  2.0  1.0    1  2.0  NaN  NaN  1.0  2.0 ...   1.0  1.0  1.0  1.0   
3    NaN NaN  1.0  NaN  NaN  NaN  NaN  1.0  1.0  1.0 ...   1.0  2.0  1.0  1.0   
4    NaN NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
5    NaN NaN  NaN  1.0    1  NaN  NaN  1.0  2.0  1.0 ...   1.0  2.0  1.0  1.0   
6    NaN NaN  1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0 ...   2.0  1.0  NaN  2.0   
7    NaN NaN  NaN  NaN  NaN  1.0  NaN  1.0  1.0  NaN ...   NaN  NaN  NaN  NaN   
8    NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN ...   NaN  NaN  NaN  NaN   
9    NaN NaN  NaN  NaN    1  1.0  NaN  NaN  NaN  NaN ...   NaN  1.0  NaN  NaN   
10   NaN NaN  NaN  NaN    1  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
11   NaN NaN  NaN  NaN  NaN  1.0  NaN  1.0  1.0  1.0 ...   2.0  1.0  1.0  2.0   
12   NaN NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN ...   1.0  NaN  1.0  NaN   
13   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
14   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  2.0 ...   NaN  NaN  NaN  NaN   
15   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0 ...   1.0  2.0  1.0  1.0   
16   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN ...   1.0  2.0  1.0  1.0   
17   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0 ...   2.0  1.0  1.0  2.0   
18   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  NaN  NaN  NaN   
19   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  NaN  NaN  NaN   
20   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  1.0  1.0  2.0   
21   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  NaN  NaN  NaN   
22   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  2.0  1.0  NaN   
23   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  1.0  NaN  1.0   
24   NaN NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  2.0  1.0  1.0   
25   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
26   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   2.0  NaN  NaN  NaN   
27   NaN NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
28   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   2.0  1.0  1.0  2.0   
29   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN  NaN   
..   ...  ..  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...  ...   
85   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  1.0  1.0   
86   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  1.0  1.0   
87   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  NaN  NaN   
88   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
89   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
90   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
91   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  1.0  NaN   
92   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  1.0  NaN   
93   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  NaN  1.0   
94   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  NaN  1.0   
95   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  1.0  NaN   
96   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
97   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
98   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
99   NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  1.0  NaN  NaN   
100  NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN  NaN   
101  NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  1.0  1.0  1.0   
102  NaN NaN  NaN  NaN  NaN  NaN  NaN